services:
  app:
    build: .
    container_name: clipping_video_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/.venv
      - /app/__pycache__
    env_file:
      - .env
    restart: unless-stopped
